quicklogic: add PolarPro3 BRAM inference
YosysHQ/yosys pull request #2703
Opened 2021-03-25 17:57 UTC by Ravenslofty

Here's the next part of the quicklogic flow: block RAM.

2021-04-10 08:40 UTC, Ravenslofty commented
Marked as draft because I'm waiting for QuickLogic to provide code to correctly use all 18 kilobits.

2022-01-11 17:03 UTC, Ravenslofty commented
Since the code to use it as an 18-kilobit RAM never materialised, and it's better to have this upstream than not, I have rebased it and am marking this as ready for review.

2022-01-24 15:13 UTC, clairexen requested changes
Can we get a source code comment explaining why two of the BRAM data bits are unused?

2022-01-24 15:16 UTC, mwkmwkmwk commented on techlibs/quicklogic/pp3_brams_map.v
> +  wire VCC, GND;
these are completely unnecessary, just write the constants inline

2025-08-25 13:16 UTC, closed without merging