Fixing old e-mail addresses and deadnames
YosysHQ/yosys pull request #2817
Opened 2021-06-07 22:43 UTC by clairexen

```
s/((Claire|Xen|Xenia|Clifford)\s+)+(Wolf|Xen)\s+<(claire|clifford)@(symbioticeda.com|clifford.at|yosyshq.com)>/Claire Xenia Wolf <claire@yosyshq.com>/gi;
s/((Nina|Nak|N\.)\s+)+Engelhardt\s+<nak@(symbioticeda.com|yosyshq.com)>/N. Engelhardt <nak@yosyshq.com>/gi;
s/((David)\s+)+Shah\s+<(dave|david)@(symbioticeda.com|yosyshq.com|ds0.me)>/David Shah <dave@ds0.me>/gi;
s/((Miodrag)\s+)+Milanovic\s+<(miodrag|micko)@(symbioticeda.com|yosyshq.com)>/Miodrag Milanovic <micko@yosyshq.com>/gi;
s,https?://www.clifford.at/yosys/,http://yosyshq.net/yosys/,g;
```

2021-06-08 00:24 UTC, mwkmwkmwk commented on Makefile
> +	echo -en 'Documentation at http://yosyshq.net/yosys/.\r\n' >> yosys-win32-mxebin-$(YOSYS_VER)/readme.txt
I'd suggest moving to https:// here

2021-06-08 00:27 UTC, mwkmwkmwk commented on manual/APPNOTE_010_Verilog_to_BLIF.tex
>  Clifford Wolf. The Yosys Open SYnthesis Suite. \\
leftover here (and in some more places in manual/)

2021-06-08 06:16 UTC, mmicko requested changes
There are couple of places where it should be fixed
1. backends/intersynth/intersynth.cc  - URL to documentation line 71
2. techlibs/ice40/abc9_model.v and techlibs/ice40/cells_sim.v - URL for icestorm should be poiting to YosysHQ since it is moved
3. SVN urls, but guess those are not moved to new domain yet
4. tests/various/muxpack.* test name with deadname, if you wish that changed as well
5. Documentation as @mwkmwkmwk pointed out

2021-06-08 06:56 UTC, gatecat commented
Is it OK to be `gatecat <gatecat@ds0.me>`? this is what I have been using in my own projects recently and in new nextpnr files.

2021-06-09 10:23 UTC, clairexen commented
New sed script:
```
# git ls-tree -r --name-only HEAD | xargs sed -i -rf ~/fixemails.sed
s/((Claire|Xen|Xenia|Clifford)\s+)+(Wolf|Xen)\s+<(claire|clifford)@(symbioticeda.com|clifford.at|yosyshq.com)>/Claire Xenia Wolf <claire@yosyshq.com>/gi;
s/((Nina|Nak|N\.)\s+)+Engelhardt\s+<nak@(symbioticeda.com|yosyshq.com)>/N. Engelhardt <nak@yosyshq.com>/gi;
s/((David)\s+)+(Shah|gatecat)\s+<(dave|david|gatecat)@(symbioticeda.com|yosyshq.com|ds0.me)>/gatecat <gatecat@ds0.me>/gi;
s/((Miodrag)\s+)+Milanovic\s+<(miodrag|micko)@(symbioticeda.com|yosyshq.com)>/Miodrag Milanovic <micko@yosyshq.com>/gi;
s,https?://www.clifford.at/yosys/|http://yosyshq.net/yosys/,https://yosyshq.net/yosys/,g;
```

2021-06-09 11:22 UTC, merged