Make user data types default to variables
YosysHQ/yosys pull request #2847
Opened 2021-06-23 15:07 UTC by bwitherspoon

Fixes #2846

A declaration beginning with a data type and without a net type (e.g.
wire) is a variable. This was handled correctly for built-in data types,
but not user-defined types.

Declaring a net with a net type keyword or a variable with the var keyword
preceding a user-defined type is not currently supported like it is with
built-in types. Adding support for this resulted in non-trivial parsing
conflicts. This handles typical usage though.

2021-06-23 17:31 UTC, zachjs requested changes
I don't believe this change is working as intended. Typenames can refer to wires, so the following test case previously produced no warnings, but complains with this change.
```SystemVerilog
module top;
    typedef wire W;
    W w = 1;
endmodule
```

I'd also like to see the above added as a test case with `logger -expect-no-warnings`.

2021-06-23 18:59 UTC, bwitherspoon commented
I learned that is invalid SV syntax when implementing this fix. Verilator, verible, and iverilog also consider it invalid syntax.

Originally I did support typedef wires by looking up the type definition and emitting an initial block or assign statement, but when I learned it was invalid syntax I went with this much simpler solution.

There a typedef should be followed by a data type but wire is a net type using the LRMs language. To declare a wire with a user defined type we need to do the following:

```systemverilog
module top;
  typedef logic W;
  wire W w = 1;
endmodule
```

which would then need to be equivalent to:

```systemverilog
module top;
  typedef logic W;
  wire W w;
  assign w = 1;
endmodule
```

However, this syntax is not yet supported. This is why I make user types unconditionally variables.

So I could support wire typdefs, but since it is invalid syntax maybe a more informative warning or a syntax error would be better?

2021-06-24 01:56 UTC, zachjs reviewed
Thank you for the clarification! This is reasonable for now, but I am definitely interested in revising the grammar to better handle, `var`, `wire`, and `typedef`.

2021-06-24 01:56 UTC, zachjs commented on tests/svtypes/typedef_initial_and_assign.ys
> +logger -expect warning "reg '\\var_3' is assigned in a continuous assignment" 1
Please add `logger -expect-no-warnings` so that the script will error if are any warnings besides those explicitly expected.

2021-06-24 21:33 UTC, bwitherspoon commented
I have revised the grammar to only allow data types in user-type definitions and raise syntax errors otherwise. This also resolves the grammar conflicts  that prevented supporting the `var` and `wire` modifiers with `typedef` types. I will submit another pull request for these changes shortly.

2021-07-06 18:09 UTC, bwitherspoon commented
Closed in favor of #2849

2021-07-06 18:09 UTC, closed without merging