Allow optional comma after last entry in enum
YosysHQ/yosys pull request #2917
Opened 2021-08-05 19:09 UTC by msinger

An extra comma is already allowed in module port lists and task/function argument lists, so I thought, why not in enum.

2021-08-05 19:50 UTC, udif commented
Adding my 2c's

I don't know exactly what Yosys supports or not, but the extra comment is not simply a "why not" item. It is an explicitly supported as part of a more general (mis)feature in the Verilog standard called "null ports" (although I personally wish it would have never been added), and applies only for non-ANSI module declarations. It is not supported by ANSI-style module declarations. I have never checked whether this applies to tasks/functions as well or not.

Feel free to follow the following to read more about it:
https://github.com/verilator/verilator/issues/2874
https://github.com/verilator/verilator/issues/2875

If it was up to me I wouldn't add it for a "why not" reason, definitely without checking first if this agrees with the standard as well as other tools.

2021-08-05 20:18 UTC, msinger commented
@udif thank you very much for that information. I wonder how they came up with that idea. :/
But as long as there are no "null names" in an `enum`, I think this optional comma would be nice to have. ^^

2021-08-05 21:03 UTC, udif commented
The question that needs to be answer is if the Yosys Verilog/SystemVerilog should adhere to the standard, or add arbitrary extensions. If the latter, I would suggest enabling these via a special read_verilog flag to enable this.

2021-08-09 15:41 UTC, zachjs requested changes
Optional commas are nice, and we are generally comfortable adding support in places where the LRM has not already ascribed a meaning to the stray comma, given the intent is likely clear. However, I'd like to avoid the noise of reindenting this whole block. Could we consider only changing the first line, or instead modifying `enum_name_list`?

2021-08-09 17:46 UTC, msinger commented
@zachjs, yes, I understand, I don't like it either to modify more than necessary, because as you said, the diff gets noisy and maybe the original author is sad if I disagree with their style.
I thought this was the best option here though. My intend was to add the extra comma in the same way it was added for the module ports and the function arguments. I can't see how I could easily add the comma to `enum_name_list` without unnecessarily adding an extra layer around it, because it references itself, which would allow unlimited extra commas in between.
I tried to match the indentation style with the surrounding code. By having the indentation not being dependent on the length of the first line, it makes it easier to make changes in the future, without the need of constantly reindenting everything. But if you prefer, then I change only the first line, but this messes up the alignment with the other lines.
What do you think?

2021-08-10 04:25 UTC, zachjs approved these changes
This is the only instance of this formatting in the parser. I'm usually not a fan of unnecessary whitespace changes, but this is well localized and restores some uniformity. For these reasons, I'm going to merge this as-is.

As a side note, there is a way to formulate such productions without a wrapping rule.
```
foos
  : foo optional_comma
  | foo ',' foos
```
I have heard that this can have a performance impact under certain setups, as all the `foo`s have to be shifted before they are reduced, but I'm not sure the potential impact is relevant here.

2021-08-10 04:25 UTC, merged