Gowin: deal with active-low tristate
YosysHQ/yosys pull request #2971
Opened 2021-08-19 17:07 UTC by pepijndevos

Now that we're adding support in Apicula for inout and tristate buffers we're finding that they are actually active-low, causing inverted behavior.

This PR matches the behavior of Nexus explained in #2916 by using an intermediate cell.
It also moves the iopadmap earlier into the process, so that there is more room to optimize away the inverter.

2021-08-19 18:17 UTC, mwkmwkmwk commented on techlibs/gowin/cells_map.v
> +	TBUF _TECHMAP_REPLACE_ (.I(I), .O(), .OEN(~OE), .O(O));
`.O` is connected twice here, please remove.

2021-08-19 18:18 UTC, mwkmwkmwk requested changes
See inline comment; also, the sim models in cells_sim need changing to account for the active-low enable.

2021-08-20 07:12 UTC, pepijndevos commented on techlibs/gowin/cells_map.v
> +	TBUF _TECHMAP_REPLACE_ (.I(I), .O(), .OEN(~OE), .O(O));
Also removed in nexus where I copied this from

2021-08-20 11:21 UTC, mwkmwkmwk requested changes
Please fix the tests.

2021-08-20 16:16 UTC, pepijndevos commented
Hm so on CI it errors on the LUT1 which is easy enough to fix, but locally it fails on the opt_equiv assertion, which I'm not sure how to deal with.

2021-08-20 16:23 UTC, mwkmwkmwk approved these changes

2021-08-20 19:21 UTC, merged