complete support for microsemi smartfusion2 and igloo2bar
YosysHQ/yosys pull request #3087
Opened 2021-11-25 08:40 UTC by tgingold-cern

This PR adds:
* BRAM cells description and mapping
* $alu support
* SYSRESET and XTLOSC cells
* fix in synth_sf2 so that yosys could be used in the LiberoSoc flow.

Only files in techlibs/sf2 are modified.

2021-11-25 12:11 UTC, Ravenslofty reviewed
I'm not all that comfortable with the `-ffinit` option here as it seems like a way of silently breaking designs; it seems strange though that the hardware cannot initialise its flops.

2021-11-25 12:56 UTC, tgingold-cern commented
smartfusion2 is flash based which could explain there is no initial ff state.

The flag is not set by default, so it's safe.
And it is not very silent: yosys reports all the unhanded init attribute.

Do you have a better suggestion ?

2021-12-06 14:41 UTC, mwkmwkmwk commented
Having an option to discard FF initialization is fine of itself, as long as it's not the default.  I'd recommend using a more descriptive name though, like `-discard-ffinit` or `-ignore-ffinit`.

Also, the current way is not quite correct: this indeed prevents `dfflegalize` from rejecting the unimplementable FFs, but leaves stray `init` attributes in the netlist (since the `cells_map.v` rules don't remove them).  I'd recommend reverting the `dfflegalize` call to its previous shape and instead running `attrmap -remove init` somewhere early in the flow (right after `proc` should be fine) if the option is set.

2021-12-06 15:10 UTC, mwkmwkmwk commented on techlibs/sf2/cells_sim.v
> +	parameter [2:0] MODE = 2'h3;
should be `[1:0]`

2021-12-08 14:47 UTC, tgingold-cern commented on techlibs/sf2/cells_sim.v
> +	parameter [2:0] MODE = 2'h3;
Sure.  Good catch!

2021-12-08 14:49 UTC, tgingold-cern commented
Thank you for your feedback, that's appreciated.
I have renamed the option to -discard-ffinit and implemented using attrmap, as advised.

2022-08-25 10:02 UTC, nakengelhardt commented
Would you mind pulling out the bram inference parts into a separate PR? We'll want to implement those with the new `memory_libmap` infrastructure instead, but the rest looks fine to merge.

2022-08-26 13:42 UTC, tgingold-cern commented
Ok, I have just updated this PR without the bram inference.  Thanks!

2022-08-29 13:41 UTC, nakengelhardt requested changes

2022-08-29 13:41 UTC, nakengelhardt commented on Makefile
> -	$(Q) if test -d abc && test -d abc/.git && ! git -C abc diff-index --quiet HEAD; then \
Why this change? The original (with `git -C`) would be preferred for us since it handles errors.

2022-08-29 13:41 UTC, nakengelhardt commented on techlibs/sf2/synth_sf2.cc
> +                        run("dfflegalize -cell $_DFFE_PN?P_ x -cell $_SDFFCE_PN?P_ x -cell $_DLATCH_PN?_ x");
Can you change this back to tabs?

2022-08-31 06:41 UTC, tgingold-cern commented
Oops, those two changes were not expected to be on this branch.  Now fixed.
Thanks!

2022-08-31 06:48 UTC, mmicko commented
Thanks @tgingold-cern will merge as soon as CI checks are done

2022-08-31 07:30 UTC, merged