-y flag for libyosys Python scripts
YosysHQ/yosys pull request #4553
Opened 2024-08-19 17:24 UTC by donn

_What are the reasons/motivation for this change?_

This adds a Python equivalent to the `-c` option, where scripts importing `libyosys` can be imported and used. 

Most of the requisite work for this was already done to enable Python passes a couple years back, so this is a relatively small changeset, and would add another option for supporting libyosys-based scripts (that does not involve PYTHONPATH shenanigans.)

_Explain how this is achieved._

Adding a new opt, `-y` (`-p` and `-P` were already taken,) and running `PyRun_SimpleFile` on `scriptfile`. Similar to `-c` for Tcl, any unprocessed arguments are passed to the script in the form of `sys.argv`.

_If applicable, please suggest to reviewers how they can test the change._

```sh
./yosys -y <(echo "
import libyosys as ys

d = ys.Design()
ys.run_pass('help', d)
print(sys.argv)") -- test argv
```

2024-08-25 12:55 UTC, donn commented
Any feedback on this? (The Verific test is failing because of security reasons- I'm a first-time contributor)

2024-08-27 03:10 UTC, KrystalDelusion commented
> Any feedback on this? (The Verific test is failing because of security reasons- I'm a first-time contributor)

That should be fixed by #4552, you may need to merge/rebase on latest main to get the fix though

2024-08-27 05:51 UTC, donn commented
Rebased on the wrong upstream for a second there but should be fine now :)

2024-09-03 14:08 UTC, donn commented
Any feedback?

2024-09-30 13:51 UTC, jix requested changes

2024-09-30 13:51 UTC, jix commented on kernel/driver.cc
> +			PyRun_SimpleString(("import os;sys.path.insert(0, os.path.dirname(os.path.abspath(\""+scriptfile+"\")))").c_str());
I think the escaping issues I mentioned on the call could be avoided using something like this instead, similar how argv is already handled:

```
  PyObject *py_path = PyUnicode_FromString(scriptfile.c_str());
  PyObject_SetAttrString(sys, "_yosys_script_path", py_path);
  Py_DECREF(py_path);
  PyRun_SimpleString("import os, sys; sys.path.insert(0, path.dirname(os.path.abspath(sys._yosys_script_path)))");
```

I tested this with a small stand-alone program and had to import both `os` and `sys` in the python snippet.

2024-09-30 13:51 UTC, jix commented on kernel/driver.cc
> +			FILE *scriptfp = fopen(scriptfile.c_str(), "r");
This also needs a check whether `scripfp` is a nullptr in case the file isn't present (or couldn't be opened for other reasons).

2024-10-07 09:02 UTC, merged