opt_merge: hashing performance and correctness
YosysHQ/yosys pull request #4677
Opened 2024-10-18 21:13 UTC by widlarizer

This is a direct remake of #4175 sans the 64-bit hash value. I'm making use of the interface in #4524 and requiring that PR (and containing its commits at the moment). Instead of xorshifts, values are sorted, though a final xorshift is included as a part of the fudge (`--hash-seed=N`) mechanism.

Additionally, I discovered opt_merge behaves incorrectly in the case of hash collisions. This suggests that this PR might in rare cases bring improvements in quality of results for flows that use opt_merge, since prior to it, hash collisions would inhibit merging. I modified the `sharemap` from a `dict<hash_t, Cell*>` to an equivalent `std::unordered_multimap` so that multiple cells can be associated with the same hash. This can't be a separate change since this bug actually broke the build just by changing how the hashes are constructed.

Sorry for the spam to code owners due to being based on the above mentioned wide-reaching PR #4524, I don't have a way of removing you from the reviewer list. The diff for this PR is not going to be very readable on github either until that's merged

2024-11-11 11:09 UTC, widlarizer commented
The current implementation regresses opt_merge runtime many times over. I'll see if `std::unordered_multimap`.
Currently, `std::unordered_multimap`, as I use it

+ maps from `hash_t` to `Cell*`
+ hashes `hash_t` with `std::hash` (unnecessary)
+ compares `Cell*`s with pointer equality

Instead it should:

+ map from `Cell*` to `Cell*`
+ hash with `hash_cell_function`
+ compare with `compare_cell_parameters_and_connections`

2024-11-13 22:05 UTC, widlarizer commented
`pool` fails to bring a clear advantage over `std::unordered_set`:

```
ibex pool
Elapsed time: 0:42.16[h:]min:sec. CPU time: user 41.87 sys 0.17 (99%). Peak memory: 164800KB.

ibex std::unordered_set
Elapsed time: 0:42.85[h:]min:sec. CPU time: user 42.56 sys 0.16 (99%). Peak memory: 164076KB.

ibex pool
Elapsed time: 0:49.41[h:]min:sec. CPU time: user 48.76 sys 0.49 (99%). Peak memory: 634672KB.

ibex std::unordered_set
Elapsed time: 0:47.62[h:]min:sec. CPU time: user 46.95 sys 0.51 (99%). Peak memory: 629852KB.
```

2024-11-18 19:06 UTC, rmlarsen commented
@widlarizer nice work!

2025-01-09 15:17 UTC, widlarizer commented
I checked for regression on the current rebased head (57ca09ee) and we're good on that

2025-01-09 20:00 UTC, rmlarsen commented
Switching to a `std::` datastructure is much appreciated!

2025-03-07 18:39 UTC, povik commented on passes/opt/opt_merge.cc
> +						std::swap(other_cell, cell);
When this happens I think we need to update known_cells so that it holds the cell which survives

2025-03-07 18:40 UTC, povik commented on passes/opt/opt_merge.cc
> +						std::swap(other_cell, cell);
Maybe this has been always a bug?

2025-03-07 18:56 UTC, povik requested changes

2025-03-07 18:56 UTC, povik commented on passes/opt/opt_merge.cc
> +							initvals.set_init(other_sig, init);
I don't understand this initvals dance but I see it was pre-existing

2025-03-07 18:56 UTC, povik commented on passes/opt/opt_merge.cc
> +			h = assign_map(cell->getPort(ID::Y)).hash_into(h);
Output shouldn't be hashed here

2025-03-08 12:35 UTC, widlarizer commented on passes/opt/opt_merge.cc
> +						std::swap(other_cell, cell);
Nice catch! After the loop you can add
```
for (auto cell : known_cells) {
	log("known_cells %s\n", log_id(cell));
}
```
and trip valgrind on `tests/opt/opt_merge_keep.ys`... that's no good

2025-03-10 10:40 UTC, widlarizer commented on passes/opt/opt_merge.cc
> +			h = assign_map(cell->getPort(ID::Y)).hash_into(h);
My bad, but I gotta say, the idea that there might be zero tests for the basic functionality of opt_merge just hasn't crossed my mind... I'll have to add some. Better late than never

2025-03-10 13:25 UTC, widlarizer commented on passes/opt/opt_merge.cc
> +							initvals.set_init(other_sig, init);
I thought this might be to avoid `FfInitVals` or `SigMap` getting notified with their monitor about the connection, but they don't use `Monitor`s so it remains a mystery

2025-03-19 22:39 UTC, KrystalDelusion approved these changes
I've only checked the fixes from @povik's requested changes, but seems fine to me.  If possible, do you have any test cases for the correctness fixes that you mentioned?  The test script added at the moment passes on latest main (and I assume given the name is just testing the basics, not the edge cases where things fall over with the current implementation)

2025-03-21 11:26 UTC, widlarizer commented
@KrystalDelusion The "many collisions case" was something I discovered when I broke the hashing function and caused everything to collide. Previously, if you had cells `a`, `b` and `c`, and they all incidentally got the same hash, and `a`!=`b` and `b`=`c`, then `a` would become the representative cell for that hash value, `b` would be checked against it and found not equal, `a` would stay as the representative, and `c` would also be checked against `a` and found not equivalent. This means that although there are two mergable cells (`b` and `c`), just because they both collide with a third non-equivalent, they wouldn't get merged. This meant that the correct functionality of the pass relied on properties of the hashing and ordering of the cell iteration, which is no good.

Testing this would require adding a flag to the pass that forces this unfortunate case, since we can't really cause it to happen externally. For the hashing done at the core of this pass, it would override the hashing function to return the same result for anything

2025-03-24 21:36 UTC, merged