Adjust `keep_hierarchy` behavior
YosysHQ/yosys pull request #4706
Opened 2024-11-05 08:36 UTC by povik

_What are the reasons/motivation for this change?_

This makes two changes to `keep_hierarchy -min_cost` to make it better suited to the task of partially preserving hierarchy for macro placement:

 * Don't count cost from submodules marked with `keep_hierarchy` towards the upper module's cost.
 * Accept a `gate_cost_equivalent` attribute as a way of specifying cost on blackboxes.

2024-11-11 12:10 UTC, widlarizer commented
> number of gates post initial mapping to fine cell, but for the macro placement use case the size of the module at the end of synthesis is more relevant

When I built this I experimented with also running opt in the flow and it didn't make much of a difference vs just techmapping, so I think this may not be as much of a problem? Anyway, it's just a knob for the user to twiddle, and users with an engineering background (the core audience) usually like that kind of arbitrary control, even if to a fault

2024-11-11 12:24 UTC, povik commented
For instance numbers I expect opt isn’t as important as the abc transformations and mapping to technology cells

2024-11-18 14:46 UTC, widlarizer requested changes

2024-12-03 10:13 UTC, povik commented on passes/hierarchy/keep_hierarchy.cc
> +		log("        When evaluating a module's cost, gates which are within a submodule\n");
That's right, fixed

2024-12-03 10:13 UTC, povik commented on README.md
> +- The `gate_cost_equivalent` attribute on a module can be used to specify
Good catch, I've moved it and mentioned the command

2024-12-03 11:17 UTC, widlarizer approved these changes

2024-12-03 11:18 UTC, merged