wreduce: Optimize signedness when possible
YosysHQ/yosys pull request #4819
Opened 2024-12-16 12:04 UTC by povik

_What are the reasons/motivation for this change?_

See the attached test case. It can happen the RTL designer has written an explicit sign extension combined with an unsigned operation. Previously this would make `wreduce` unable to reduce the size of operands.

_Explain how this is achieved._

We detect conditions under which the signedness of the operands is arbitrary (because the input operands are fully sized wrt to the output and the operation is one of addition, subtraction, multiplication). Under these conditions estimate the size of the reduced operator if we make the operands signed or unsigned, and then flip the signedness accordingly before the usual operand reduction of `wreduce` takes place.

2024-12-18 20:15 UTC, widlarizer requested changes
Good catch of a missed optimization, but I can't in good conscience convince myself of its correctness yet

2024-12-19 09:26 UTC, povik commented on passes/opt/wreduce.cc
> +				signed_size = max(reduced_opsize(sig_a, true), reduced_opsize(sig_b, true));
This is not the result size, this is an estimate of the operator's cost. I will rename

2024-12-19 09:26 UTC, povik commented on passes/opt/wreduce.cc
> +				signed_size = reduced_opsize(sig_a, true) * reduced_opsize(sig_b, true);
Ditto here. An estimate of the multiplier's cost

2024-12-19 09:46 UTC, widlarizer commented on passes/opt/wreduce.cc
> +				signed_size = max(reduced_opsize(sig_a, true), reduced_opsize(sig_b, true));
Got it, makes sense

2025-01-06 14:26 UTC, clairexen approved these changes
Noice! (LGTM)

2025-01-06 14:27 UTC, povik commented
Thanks Claire!

2025-01-06 14:27 UTC, merged